import { Router, Request, Response } from 'express';
import PDFDocument from 'pdfkit';
import { pool } from '../../config/database';
import { authenticate, authorize } from '../../middleware/auth.middleware';
import { asyncHandler } from '../../middleware/error.middleware';

const router = Router();
router.use(authenticate);

router.get('/report-card/:examId/:studentId/pdf', asyncHandler(async (req: Request, res: Response) => {
  const { examId, studentId } = req.params;

  const { rows: studentRows } = await pool.query(
    `SELECT s.admission_number, s.roll_number, s.gender,
            u.first_name, u.last_name,
            c.name AS class_name, sec.name AS section_name,
            ay.name AS academic_year
     FROM students s
     JOIN users u ON u.id = s.user_id
     LEFT JOIN sections sec ON sec.id = s.section_id
     LEFT JOIN classes c ON c.id = sec.class_id
     LEFT JOIN academic_years ay ON ay.id = c.academic_year_id
     WHERE s.id = $1`,
    [studentId]
  );

  const { rows: marksRows } = await pool.query(
    `SELECT sub.name AS subject, sub.code,
            m.marks_obtained, m.practical_marks, m.is_absent,
            es.max_marks, es.passing_marks,
            CASE WHEN m.is_absent THEN 'AB'
                 WHEN (m.marks_obtained + COALESCE(m.practical_marks,0)) >= es.passing_marks THEN 'P'
                 ELSE 'F' END AS status
     FROM marks m
     JOIN subjects sub ON sub.id = m.subject_id
     JOIN exam_schedules es ON es.exam_id = m.exam_id AND es.subject_id = m.subject_id
     WHERE m.exam_id = $1 AND m.student_id = $2
     ORDER BY sub.name`,
    [examId, studentId]
  );

  const { rows: rcRows } = await pool.query(
    'SELECT * FROM report_cards WHERE exam_id = $1 AND student_id = $2',
    [examId, studentId]
  );

  const student = studentRows[0];
  const rc = rcRows[0];

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="report-card-${student?.admission_number || studentId}.pdf"`);
  doc.pipe(res);

  // Header
  doc.fontSize(20).fillColor('#1a3c6e').text('शहीद राम सिंह विद्यालय', { align: 'center' });
  doc.fontSize(12).fillColor('#333').text('Shaheed Ram Singh Vidyalaya', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(16).fillColor('#1a3c6e').text('REPORT CARD', { align: 'center' });
  doc.moveDown();

  if (student) {
    doc.fontSize(11).fillColor('#000');
    doc.text(`Student Name: ${student.first_name} ${student.last_name}`, 50);
    doc.text(`Admission No: ${student.admission_number}  |  Roll No: ${student.roll_number || 'N/A'}`, 50);
    doc.text(`Class: ${student.class_name} - ${student.section_name}  |  Academic Year: ${student.academic_year}`, 50);
    doc.moveDown();
  }

  // Table header
  doc.fontSize(10).fillColor('#fff').rect(50, doc.y, 500, 20).fill('#1a3c6e');
  const tableY = doc.y - 15;
  doc.fillColor('#fff').text('Subject', 55, tableY);
  doc.text('Max', 250, tableY);
  doc.text('Obtained', 310, tableY);
  doc.text('Status', 420, tableY);
  doc.moveDown(1.5);

  let altRow = false;
  for (const mark of marksRows) {
    if (altRow) doc.rect(50, doc.y - 3, 500, 18).fill('#f0f4ff');
    doc.fillColor('#000').text(mark.subject, 55, doc.y - 2);
    doc.text(String(mark.max_marks), 250, doc.y - 18);
    doc.text(mark.is_absent ? 'AB' : String(mark.marks_obtained || 0), 310, doc.y - 18);
    const statusColor = mark.status === 'P' ? '#16a34a' : '#dc2626';
    doc.fillColor(statusColor).text(mark.status, 420, doc.y - 18);
    doc.moveDown(0.3);
    altRow = !altRow;
  }

  doc.moveDown();
  doc.fillColor('#1a3c6e').fontSize(12);
  if (rc) {
    doc.text(`Total: ${rc.total_marks} / ${rc.max_total_marks}  |  Percentage: ${rc.percentage}%  |  Grade: ${rc.grade}`, 50);
    doc.text(`Class Rank: ${rc.rank_in_class || 'N/A'}`, 50);
  }

  doc.moveDown(2);
  doc.fillColor('#666').fontSize(9).text('Principal Signature: ____________________', 50);
  doc.text('Class Teacher Signature: ____________________', 300);
  doc.moveDown();
  doc.text('Generated by शहीद राम सिंह विद्यालय ERP System', { align: 'center' });

  doc.end();
}));

router.get('/attendance/export', authorize('admin', 'teacher'), asyncHandler(async (req: Request, res: Response) => {
  const { sectionId, startDate, endDate } = req.query;

  const { rows } = await pool.query(
    `SELECT s.admission_number, u.first_name, u.last_name,
            COUNT(*) AS total_days,
            COUNT(*) FILTER (WHERE a.status IN ('present','late')) AS present,
            COUNT(*) FILTER (WHERE a.status = 'absent') AS absent,
            ROUND(COUNT(*) FILTER (WHERE a.status IN ('present','late'))::DECIMAL / NULLIF(COUNT(*),0) * 100, 2) AS percentage
     FROM students s
     JOIN users u ON u.id = s.user_id
     LEFT JOIN attendance a ON a.student_id = s.id AND a.date BETWEEN $2 AND $3
     WHERE s.section_id = $1 AND s.admission_status = 'active'
     GROUP BY s.id, s.admission_number, u.first_name, u.last_name
     ORDER BY percentage DESC`,
    [sectionId, startDate, endDate]
  );

  const ExcelJS = require('exceljs');
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Attendance Report');

  sheet.columns = [
    { header: 'Admission No', key: 'admission_number', width: 15 },
    { header: 'First Name', key: 'first_name', width: 20 },
    { header: 'Last Name', key: 'last_name', width: 20 },
    { header: 'Total Days', key: 'total_days', width: 12 },
    { header: 'Present', key: 'present', width: 10 },
    { header: 'Absent', key: 'absent', width: 10 },
    { header: 'Percentage', key: 'percentage', width: 12 },
  ];

  sheet.addRows(rows);
  sheet.getRow(1).font = { bold: true };

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', 'attachment; filename=attendance-report.xlsx');
  await workbook.xlsx.write(res);
  res.end();
}));

export default router;
